name: "Check"
on:
  workflow_dispatch:

  schedule:
    - cron: "0 14 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        env:
          INCREMENTAL: "true"
          QUICKLY: "true"
          PARALLET: "30"
        run: |
          ./hack/diff.sh
      - name: Update badge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Generated for update gist
          BADGE_PREFIX: "git://${{ github.repository }}/gh-pages"
          QUICKLY: "true"  
        run: |
          wget https://github.com/wzshiming/putingh/releases/download/v0.6.2/putingh_linux_amd64 -O /usr/local/bin/putingh && chmod +x /usr/local/bin/putingh
          ./hack/badge.sh
          GH_TOKEN="${GH_TOKEN}" putingh "${BADGE_PREFIX}/cr-sync-badge.svg" badge.svg
          GH_TOKEN="${GH_TOKEN}" putingh "${BADGE_PREFIX}/cr-sync.log" sync.log
