name: Sync

on:
  schedule:
    - cron: "0 */4 * * *"

  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login Registry
        env:
          GH_ID: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo mkdir -p /run/containers && sudo chmod 777 /run/containers
          skopeo login -u ${GH_ID} -p ${GH_TOKEN} ghcr.io
      - name: Sync Images
        env:
          INCREMENTAL: "true"
          QUICKLY: "true"
          SYNC: "true"
          PARALLET: "30"
        run: |
          ./hack/diff.sh
