name: Sync

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Sync Docker Images
        env:
          GH_ID: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo skopeo login -u ${GH_ID} -p ${GH_TOKEN} ghcr.io
          sudo ./hack/sync.sh
